image:
  source:
      type: git
      uri: file:///vagrant/scs-elasticsearch
  engine:
    method: docker
  config:
    main:
      cluster: 'testme-default'
      es_env_opts:
        ES_MAX_MEM: 128M 
        ES_MIN_MEM: 128M
container:
  name:
    environment: dev
    service: scs-elasticsearch
    role: test
  dependency:
    provide:
      api_http:
        method: disco
      transport_tcp:
        method: disco
    require:
      transport_tcp:
        method: disco
    volume:
      data:
        method: local
